### PR TITLE
Fix parameter handling

### LINKED ISSUE #1431: Weird Behavior for byte[] array in Hibernate Objects
Attempting to utilize a class that has a field mapping byte[] to Blob.  Getting the following error:

```
[B cannot be cast to [Ljava.lang.Object;
! java.lang.ClassCastException: [B cannot be cast to [Ljava.lang.Object;
! at com.querydsl.jpa.hibernate.HibernateUtil.setValue(HibernateUtil.java:71) ~[querydsl-jpa-4.0.2.jar:na]
! at com.querydsl.jpa.hibernate.HibernateUtil.setConstants(HibernateUtil.java:63) ~[querydsl-jpa-4.0.2.jar:na]
! at com.querydsl.jpa.hibernate.AbstractHibernateQuery.createQuery(AbstractHibernateQuery.java:105) ~[querydsl-jpa-4.0.2.jar:na]
! at com.querydsl.jpa.hibernate.AbstractHibernateQuery.createQuery(AbstractHibernateQuery.java:97) ~[querydsl-jpa-4.0.2.jar:na]
! at com.querydsl.jpa.hibernate.AbstractHibernateQuery.fetch(AbstractHibernateQuery.java:174) ~[querydsl-jpa-4.0.2.jar:na]
```

### PR DESCRIPTION
**Pull request by timowest**
Fixes #1431

### CODE REVIEW

File: querydsl-jpa/src/test/java/com/querydsl/jpa/AbstractJPATest.java [hunk 1]
```diff
@@ -544,13 +544,13 @@ public void DistinctResults() {
...
         assertEquals(200002, query().from(cat).select(cat.birthdate.yearMonth()).fetchFirst().intValue());
         assertEquals(2,      query().from(cat).select(cat.birthdate.month()).fetchFirst().intValue());
         //query().from(cat).select(cat.birthdate.week());
-        assertEquals(2,      query().from(cat).select(cat.birthdate.dayOfMonth()).fetchFirst().intValue());
-        assertEquals(3,      query().from(cat).select(cat.birthdate.hour()).fetchFirst().intValue());
-        assertEquals(4,      query().from(cat).select(cat.birthdate.minute()).fetchFirst().intValue());
+        assertEquals(2, query().from(cat).select(cat.birthdate.dayOfMonth()).fetchFirst().intValue());
+        assertEquals(3, query().from(cat).select(cat.birthdate.hour()).fetchFirst().intValue());
+        assertEquals(4, query().from(cat).select(cat.birthdate.minute()).fetchFirst().intValue());
         assertEquals(0,      query().from(cat).select(cat.birthdate.second()).fetchFirst().intValue());
```
Comment (johnktims) [inline querydsl-jpa/src/test/java/com/querydsl/jpa/AbstractJPATest.java]: The spacing is off a little here.

**Comment by Shredder121** [comment]
This looks good to me
