### PR TITLE
Fix listener handling

### LINKED ISSUE #1786: Pooled Connection doesn't work in SQLMergeClause with compositeMerge
Dear all,

I really appreciate your improvements regarding connection pooling in the last version. Currently, I am using QueryDSL 4.0.7 at a client's project and experienced some issue while using BasicDataSources for our Oracle-connectivity and the new connection pooling mechanism of QueryDSL. In detail, I would like to use the SQLMergeClause, but it doesn't work. The OracleTemplates don't support nativeMerge (isNativeMerge() returns false). During the invocation of the SQLMergeClause.execute()-method the method executeCompositeMerge() is run and here is the problem. This method begins with an invocation of hasRow() which closes the used connection. But this connection keeps referenced and is reused for the following update or insert query of that method. The result is "SQLExeption: Connection is null". From my point of view the connection has to be nulled in the SQLMergeClause when it is going to be closed. In this case the DataSource would deliver a new connection from its pool.
Are you aware of this problem? Or do you have any suggestion how I can fix this problem?

Thank you and kind regards
Lukas

### PR DESCRIPTION
**Pull request by timowest**
Fixes #1786

### CODE REVIEW

File: querydsl-sql/src/main/java/com/querydsl/sql/SQLListeners.java [hunk 1]
```diff
@@ -245,4 +245,9 @@ public void exception(final SQLListenerContext context) {
             listener.exception(context);
         }
     }
+
+    public Set<SQLDetailedListener> getListeners() {
```
Comment (Shredder121) [inline querydsl-sql/src/main/java/com/querydsl/sql/SQLListeners.java]: Does this specifically need to be a `Set`?
Just wondering if you had plans with this.

**Comment by Shredder121** [comment]
Looks good.

File: querydsl-sql/src/main/java/com/querydsl/sql/SQLListeners.java (hunk 1 above)
Comment (timowest) [inline querydsl-sql/src/main/java/com/querydsl/sql/SQLListeners.java]: I like the emphasis on no duplicates instead of ordering, although a LinkedHashSet is used

Comment (Shredder121) [inline querydsl-sql/src/main/java/com/querydsl/sql/SQLListeners.java]: Okay, since we only iterate over it to copy it, so `Iterable` would work, but if you need to add anything `Collection` would work as well.
Keeping it `Set` is also an option, I was just wondering though.

**Comment by johnktims** [comment]
Looks good to me, too.
