### PR TITLE
Fix setting root path to null

### LINKED ISSUE #1686: set null values to column causes NullPointerException when inserting or updating
I don't use class generation for mapping my entities. I'm using queryDSL version 4.0.5

Here is my code :

    SQLTemplates templates = MySQLTemplates.builder().printSchema().build();
    Configuration configuration = new Configuration( templates );

    try
    {
        Class.forName( "com.mysql.jdbc.Driver" );

        final Connection connection = DriverManager.getConnection( "jdbc:mysql://localhost:3306/test", "root", "" );

        SQLQuery sqlQuery = new SQLQuery( connection, configuration );

        // querying
        NumberPath< Long > volume = Expressions.numberPath( Long.class, "volume" );

        RelationalPathBase< Object > r = new RelationalPathBase< Object >( Object.class, "", "test", "mstf" );

        Provider< java.sql.Connection > provinv = new Provider< Connection >()
        {

            @Override
            public Connection get()
            {
                return connection;
            }
        };

        SQLQueryFactory queryFactory = new SQLQueryFactory( configuration, provinv );

        queryFactory.update( r ).setNull( volume ).execute();

    }
    catch( Exception e )
    {
        e.printStackTrace();
    }
When executing, I got a wonderful NullPointerException because of this code in class ColumnMetadata:

public int getJdbcType() {
    return jdbcType;
}
Of course we have a jdbcType of type INTEGER, it is null and we must return an int...

### PR DESCRIPTION
**Pull request by Shredder121**
Fixes #1686

### CODE REVIEW

File: querydsl-sql/src/main/java/com/querydsl/sql/Configuration.java [hunk 1]
```diff
@@ -223,7 +223,7 @@ public String getColumnOverride(SchemaAndTable key, String column) {
     @SuppressWarnings({ "unchecked", "rawtypes" })
     public <T> void set(PreparedStatement stmt, Path<?> path, int i, T value) throws SQLException {
         if (Null.class.isInstance(value)) {
-            Integer sqlType = path != null ? ColumnMetadata.getColumnMetadata(path).getJdbcType() : null;
+            Integer sqlType = path != null && !path.getMetadata().isRoot() ? ColumnMetadata.getColumnMetadata(path).getJdbcType() : null;
```
Comment (timowest) [inline querydsl-sql/src/main/java/com/querydsl/sql/Configuration.java]: The test case is ok, but I'd fix this differently, since root path usage is only one case where this breaks. Maybe
```
Integer sqlType = null;
if (path) {
    ColumnMetadata metadata = ColumnMetadata.getColumnMetadata(path);
    if (metadata.hasJdbcType()) {
        jdbcType = metadata.getJdbcType();
    }
}
```

**Comment by timowest** [comment]
Looks good now

**Comment by johnktims** [comment]
Looks good to me.
