### PR TITLE
Simplify OperatorImpl serialization

### LINKED ISSUE #1237: Concurrency Issue Loading Ops and OperatorImpl
Whenever `com.mysema.query.types.OperatorImpl` and `com.mysema.query.types.Ops` are loaded simultaneously loaded a deadlock is reached.

The following code could be used to reproduce the issue:

```java
import org.junit.Test;

import com.mysema.query.jpa.impl.JPAQuery;

public class CycleClassInitDependencyTest {

	@Test(timeout = 2000)
	public void test() throws InterruptedException {

		// If class is loaded before hand it will work for example:
		// System.out.println(Ops.DateTimeOps.DATE);

		// each thread wants
		Thread t1 = new Thread(new LoadClassRunnable("com.mysema.query.types.OperatorImpl"));
		Thread t2 = new Thread(new LoadClassRunnable("com.mysema.query.types.Ops"));
		t1.start();
		t2.start();

		// trying to create anything depending on Ops class for instance:
		// JPAQuery -> JPQLTemplates -> Ops
		new JPAQuery();

	}

	public class LoadClassRunnable implements Runnable {

		private String classToLoad;

		public LoadClassRunnable(String classToLoad) {
			this.classToLoad = classToLoad;
		}

		public void run() {
			try {
				Class.forName(classToLoad);
			} catch (ClassNotFoundException e) {
				e.printStackTrace();
			}
		}

	}

}
```

A jstack relevant part of the execution of code exposed above is:
```
"OpslLoading        " prio=10 tid=0x00007f47a4003000 nid=0x2dd3 in Object.wait() [0x00007f47b7cfb000]
   java.lang.Thread.State: RUNNABLE
	at com.mysema.query.types.Ops.<clinit>(Ops.java:30)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:188)
	at CycleClassInitDependencyTest$LoadClassRunnable.run(CycleClassInitDependencyTest.java:37)
	at java.lang.Thread.run(Thread.java:722)

"OperatorImplLoading" prio=10 tid=0x00007f47a4001800 nid=0x2dd2 in Object.wait() [0x00007f47b7dfb000]
   java.lang.Thread.State: RUNNABLE
	at sun.misc.Unsafe.ensureClassInitialized(Native Method)
	at sun.reflect.UnsafeFieldAccessorFactory.newFieldAccessor(UnsafeFieldAccessorFactory.java:43)
	at sun.reflect.ReflectionFactory.newFieldAccessor(ReflectionFactory.java:140)
	at java.lang.reflect.Field.acquireFieldAccessor(Field.java:949)
	at java.lang.reflect.Field.getFieldAccessor(Field.java:930)
	at java.lang.reflect.Field.get(Field.java:372)
	at com.mysema.query.types.OperatorImpl.<clinit>(OperatorImpl.java:42)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:188)
	at CycleClassInitDependencyTest$LoadClassRunnable.run(CycleClassInitDependencyTest.java:37)
	at java.lang.Thread.run(Thread.java:722)

"Thread-0" prio=10 tid=0x00007f47ec205000 nid=0x2dd1 in Object.wait() [0x00007f47b7efc000]
   java.lang.Thread.State: RUNNABLE
	at com.mysema.query.types.Templates.<init>(Templates.java:50)
	at com.mysema.query.types.Templates.<init>(Templates.java:38)
	at com.mysema.query.types.Templates.<clinit>(Templates.java:27)
	at com.mysema.query.jpa.impl.JPAQuery.<init>(JPAQuery.java:35)
	at CycleClassInitDependencyTest.test(CycleClassInitDependencyTest.java:23)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$StatementThread.run(FailOnTimeout.java:74)
```

### PR DESCRIPTION
**Pull request by timowest**
Fixes #1237

### CODE REVIEW

File: querydsl-jpa/src/test/java/com/mysema/query/jpa/CycleClassInitDependencyTest.java [hunk 1]
```diff
@@ -0,0 +1,45 @@
...
+
+        // each thread wants
+        Thread t1 = new Thread(new LoadClassRunnable("com.mysema.query.types.OperatorImpl"));
+        Thread t2 = new Thread(new LoadClassRunnable("com.mysema.query.types.Ops"));
+        t1.start();
+        t2.start();
+
+        // trying to create anything depending on Ops class for instance:
+        // JPAQuery -> JPQLTemplates -> Ops
+        new JPAQuery();
```
Comment (Shredder121) [inline querydsl-jpa/src/test/java/com/mysema/query/jpa/CycleClassInitDependencyTest.java]: I will move this to core, since it is also well reproducible there and more local to the source being tested, okay?
Also, you and your "no newline at end of file" ;)

**Comment by Shredder121** [comment]
I also think it is a good idea to make a unit test that validates the naming convention of Ops fields.
This way the error detection is done using that test, and not at runtime, or (de)serialization tests.

**Comment by timowest** [comment]
Which surefire improvements do you mean?

**Comment by Shredder121** [comment]
I meant #1238

**Comment by timowest** [comment]
I thought I'd make a separate PR for that, because the targets are also different.

**Comment by Shredder121** [comment]
Also, the targets are indeed different.
Then it's okay and a separate pull request is in order.

File: querydsl-core/src/main/java/com/mysema/query/types/OperatorImpl.java [hunk 2]
```diff
@@ -81,4 +58,18 @@ public String toString() {
     public int hashCode() {
         return hashCode;
     }
+
+    private Object readResolve() throws ObjectStreamException {
+        try {
+            String[] names = id.split("#");
+            Field opField = Class.forName(names[0]).getDeclaredField(names[1]);
```
Comment (Shredder121) [inline querydsl-core/src/main/java/com/mysema/query/types/OperatorImpl.java]: Consider using `getField()` instead, it's implementation in OpenJDK 8 seems more performant.
Also the semantics of that method apply better in this case, since it is a public field.

Comment (Shredder121) [inline querydsl-core/src/main/java/com/mysema/query/types/OperatorImpl.java]: *EDIT: I think there is no difference, it is your call.*

Comment (timowest) [inline querydsl-core/src/main/java/com/mysema/query/types/OperatorImpl.java]: Maybe `getField` because of the semantics.

**Comment by Shredder121** [comment]
Just a small note.
This can not be used as a regression test, as I am fairly sure that whenever surefire reaches this test class, Ops and OperatorImpl might already be loaded.
But for this case, we fixed it.

**Comment by timowest** [comment]
Shall we add a test that uses a fresh classloader?

**Comment by Shredder121** [comment]
Yes, I think that should do it.
Could you also put the erroneous loading back to see if it works?

**Comment by timowest** [comment]
Yes, I will test it also with the old logic.

**Comment by timowest** [comment]
Added the fresh classloader usage and verified that it works without the fix.

**Comment by timowest** [comment]
I was sloppy in my testing, the fresh class loader requirement might need a customer runner.

**Comment by Shredder121** [comment]
Why? didn't it work?
A Thread seems to inherit the parent's contextClassLoader.

**Comment by timowest** [comment]
Overriding the contextClassLoader worked, but it didn't affect the classloading of the test class.

**Comment by Shredder121** [comment]
I fixed it now. Class.forName can take a ClassLoader argument.
Furthermore, I found a better way to create the URLClassLoader, so I'll commit that.
Also, when creating **fresh** ClassLoaders, it must not have a parent ClassLoader.

Even though the *test* is not the same as was reported, it tests the same, I have verified that it now works as expected.

**Comment by timowest** [comment]
@Shredder121 Shall we merge this now?

**Comment by Shredder121** [comment]
Yes, I think this now works as expected. I will merge it.
Do you think it could be worthwhile to extract the fresh classloader part to a junit rule?

**Comment by timowest** [comment]
If it affects only the context class loader then maybe not, if it guarantees a fully independent classloading of the test class, then yes, because otherwise the contract might not be very clear.

**Comment by Shredder121** [comment]
There you have a point. I think it is better like this then.
