### PR TITLE
Fix isNotEmpty bug in mongodb serialization

### LINKED ISSUE #1264: MongodbSerializer does not serialize isNotEmpty() properly
Original link: http://stackoverflow.com/questions/29104204/querydsl-isnotempty-expression-failing

There appears to be a serialization error in `MongodbSerializer` for
```java
BooleanExpression expr = qa.matches.isNotEmpty();
Iterable<A> result = aRepo.findAll(expr);

assertThat(result, is(not((emptyIterable()))));
```

` MongodbSerializer` is spitting out
```json
{ "$or" : { "$not" : [ { "matches" : [ ]} , { "matches" : { "$exists" : false}}]}}
```
which fails when I paste it into mongo.

```
> db.a.find({ "$or" : { "$not" : [ { "matches" : [ ]} , { "matches" : { "$exists" : false}}]}})
Error: error: {
	"$err" : "Can't canonicalize query: BadValue $or needs an array",
	"code" : 17287
}
> 
```

I rewrote the query as
```
> db.a.find({ "$or" : [ { "matches" : {$ne: [ ]}}, { "matches" : { "$exists" : false}}]}).pretty()
{
	"_id" : "a1",
	"_class" : "querydsldemo.A",
	"matches" : [
		{
			"_id" : ObjectId("55088ec4e4b0b6e56e76b1d6"),
			"name" : "b1"
		},
		{
			"_id" : ObjectId("55088ec4e4b0b6e56e76b1d7"),
			"name" : "b2"
		}
	]
}
{ "_id" : "a3", "_class" : "querydsldemo.A" }
```
and then further simplified it as
```
> db.a.find({ "matches" : {$ne: [ ]}}).pretty()
{
	"_id" : "a1",
	"_class" : "querydsldemo.A",
	"matches" : [
		{
			"_id" : ObjectId("55088ec4e4b0b6e56e76b1d6"),
			"name" : "b1"
		},
		{
			"_id" : ObjectId("55088ec4e4b0b6e56e76b1d7"),
			"name" : "b2"
		}
	]
}
{ "_id" : "a3", "_class" : "querydsldemo.A" }
> 
```
but I don't know if that's robust enough.

### PR DESCRIPTION
**Pull request by johnktims**
Fixes #1264 

I backported the fix and verified that the tests in the original SO issue pass.

### CODE REVIEW

File: querydsl-mongodb/src/main/java/com/querydsl/mongodb/MongodbSerializer.java [hunk 1]
```diff
@@ -127,6 +127,11 @@ public Object visit(Operation<?> expr, Void context) {
             if (subOp == Ops.IN) {
                 return visit(OperationImpl.create(Boolean.class, Ops.NOT_IN, subOperation.getArg(0),
                         subOperation.getArg(1)), context);
+            } else if (subOp == Ops.COL_IS_EMPTY) {
```
Comment (timowest) [inline querydsl-mongodb/src/main/java/com/querydsl/mongodb/MongodbSerializer.java]: alternatively this could be also a general inversion of `$or` to `$nor`

Comment (johnktims) [inline querydsl-mongodb/src/main/java/com/querydsl/mongodb/MongodbSerializer.java]: Can you give me a little more detail? I don't think I understand.

Comment (timowest) [inline querydsl-mongodb/src/main/java/com/querydsl/mongodb/MongodbSerializer.java]: I meant to detect $or expressions by looking at the nested result and
replacing $or with $nor.

Comment (Shredder121) [inline querydsl-mongodb/src/main/java/com/querydsl/mongodb/MongodbSerializer.java]: Do you mean instead of relying on the implementation of `COL_IS_EMPTY` (which uses $or) detecting $or and change that to $nor?
How deep do you want to detect?
If there is an AND involved, with two ORs which have two leaves (`x.isEmpty().and(y.isEmpty()).not()` it could cause problems.
Does Inverting the $or then work?

Comment (timowest) [inline querydsl-mongodb/src/main/java/com/querydsl/mongodb/MongodbSerializer.java]: Yes, that's what I mean, and only on the first level. Replacing the top level $or with $nor should work.

**Comment by timowest** [comment]
@johnktims Could you also add a test in `MongodbQueryTest`?

**Comment by timowest** [comment]
I suggest to test for all predicates in `MongodbQueryTest` also the negation via `predicate.not()`. That way we might catch also other similar issues.

**Comment by Shredder121** [comment]
I agree.
I have also looked at other [logical operators](http://docs.mongodb.org/manual/reference/operator/query-logical/), but there are not any special ones we need to consider.

**Comment by timowest** [comment]
I'll push soon some further improvements.

**Comment by Shredder121** [comment]
Can you also update this branch while you are at it?
There seem to have been simultaneous changes to the import order of MongodbQueryTest.

File: querydsl-mongodb/src/main/java/com/querydsl/mongodb/MongodbSerializer.java [hunk 2]
```diff
@@ -118,19 +119,30 @@ public Object visit(Operation<?> expr, Void context) {
...
                 return visit(OperationImpl.create(Boolean.class, Ops.NOT_IN, subOperation.getArg(0),
                         subOperation.getArg(1)), context);
-            } else if (subOp != Ops.EQ && subOp != Ops.STRING_IS_EMPTY) {
-                return asDBObject(key, asDBObject("$not", arg.get(key)));
+            } else if (arg.size() == 1) {
+                Map.Entry<String, Object> entry = arg.entrySet().iterator().next();
+                if (entry.getKey().equals("$or")) {
+                    return asDBObject("$nor", entry.getValue());
+                } else if (entry.getKey().equals("$and")) {
+                    return asDBObject("$nand", entry.getValue());
```
Comment (Shredder121) [inline querydsl-mongodb/src/main/java/com/querydsl/mongodb/MongodbSerializer.java]: Where did you find this operator?

**Comment by timowest** [comment]
There are still failing test cases, for example `{ "age" : { "$not" : { "$gte" : 20 , "$lte" : 30}}}`.

It seems to be interpreted as `(not (age >= 20)) and (not (age <= 30))` instead of `not (age >= 20 and age <= 30))`.

File: querydsl-mongodb/src/main/java/com/querydsl/mongodb/MongodbSerializer.java (hunk 2 above)
Comment (Shredder121) [inline querydsl-mongodb/src/main/java/com/querydsl/mongodb/MongodbSerializer.java]: Relevant SO post:
http://stackoverflow.com/questions/20810698/mongodb-how-to-query-with-nand-operator.

Comment (timowest) [inline querydsl-mongodb/src/main/java/com/querydsl/mongodb/MongodbSerializer.java]: Good point, I'll fix it.

**Comment by timowest** [comment]
@johnktims @Shredder121 Is this good to merge?

**Comment by johnktims** [comment]
I only visually inspected it but it looks good to me.
