### PR TITLE
Delay constant initialization via static inner class

### LINKED ISSUE #1668: NumberExpression class init deadlock
(Found using version 4.0.3, suspected problem persists in head revision)

We have been encountering a class init deadlock in our system. I believe I have tracked it to be because of com.querydsl.core.types.dsl.NumberExpression:38 calling in static init:

    private static final NumberExpression<Double> random = Expressions.numberOperation(Double.class, MathOps.RANDOM);

Which requires loading of com.querydsl.core.types.dsl.Expressions. However, another thread may end up concurrently loading _that_ one, leading to Expressions:612:

    return new NumberTemplate<T>(cl, template, args);

Which induces loading of NumberTemplate, which induces loading of NumberExpression, and we have a deadlock. I may be wrong as I have never really delved into QueryDSL source. Please find below the significant portions of a thread dump:

	Thread 22: (state = BLOCKED)
	 - com.querydsl.core.types.dsl.NumberExpression.<clinit>() @bci=9, line=38 (Interpreted frame)
	 - com.querydsl.core.types.dsl.BeanPath.createNumber(java.lang.String, java.lang.Class) @bci=1, line=248 (Interpreted frame)
	 - my.querydsl.generated.domain.QDomainObjectA.<init>(java.lang.String) @bci=20, line=27 (Interpreted frame)
	 - my.querydsl.generated.domain.QDomainObjectA.<clinit>() @bci=6, line=25 (Interpreted frame)

	Thread 21: (state = BLOCKED)
	 - com.querydsl.core.types.dsl.Expressions.numberTemplate(java.lang.Class, com.querydsl.core.types.Template, com.google.common.collect.ImmutableList) @bci=0, line=612 (Interpreted frame)
	 - com.querydsl.core.types.dsl.Expressions.numberTemplate(java.lang.Class, java.lang.String, java.lang.Object[]) @bci=9, line=573 (Interpreted frame)
	 - com.querydsl.core.types.dsl.Expressions.<clinit>() @bci=8, line=32 (Interpreted frame)
	 - com.querydsl.core.types.dsl.DateExpression.currentDate(java.lang.Class) @bci=8, line=56 (Interpreted frame)
	 - com.querydsl.core.types.dsl.DateExpression.<clinit>() @bci=2, line=36 (Interpreted frame)
	 - com.querydsl.core.types.dsl.BeanPath.createDate(java.lang.String, java.lang.Class) @bci=1, line=190 (Interpreted frame)
	 - my.querydsl.generated.domain.QDomainObjectB.<init>(java.lang.String) @bci=20, line=27 (Interpreted frame)
	 - my.querydsl.generated.domain.QDomainObjectB.<clinit>() @bci=6, line=25 (Interpreted frame)

### PR DESCRIPTION
**Pull request by timowest**
Fixes #1668

### CODE REVIEW

File: querydsl-core/src/main/java/com/querydsl/core/types/ConstantImpl.java [hunk 1]
```diff
@@ -28,32 +28,34 @@
 
     private static final int CACHE_SIZE = 256;
 
-    @SuppressWarnings({"rawtypes", "unchecked"}) //generic array creation not possible
-    private static final Constant<Character>[] CHARACTERS = new Constant[CACHE_SIZE];
+    private static final Constant<Boolean> FALSE = new ConstantImpl<Boolean>(Boolean.FALSE);
```
Comment (johnktims) [inline querydsl-core/src/main/java/com/querydsl/core/types/ConstantImpl.java]: Using `create(false)` would utilize the cache instead of creating another instance, right?

Comment (timowest) [inline querydsl-core/src/main/java/com/querydsl/core/types/ConstantImpl.java]: Yes, but here we can't use it

Comment (Shredder121) [inline querydsl-core/src/main/java/com/querydsl/core/types/ConstantImpl.java]: Why didn't you also move these in the `Constants` class?

Comment (timowest) [inline querydsl-core/src/main/java/com/querydsl/core/types/ConstantImpl.java]: Yes, I'll move them, initially I thought they could be out, since it's only two boolean constants, but for consistency ...

File: querydsl-core/src/main/java/com/querydsl/core/types/ConstantImpl.java [hunk 2]
```diff
@@ -28,50 +28,52 @@
 
     private static final int CACHE_SIZE = 256;
 
-    @SuppressWarnings({"rawtypes", "unchecked"}) //generic array creation not possible
-    private static final Constant<Character>[] CHARACTERS = new Constant[CACHE_SIZE];
```
Comment (Shredder121) [inline querydsl-core/src/main/java/com/querydsl/core/types/ConstantImpl.java]: Is it also possible to reorder these to the original ordering?
Or do you want it in this order?

Comment (Shredder121) [inline querydsl-core/src/main/java/com/querydsl/core/types/ConstantImpl.java]: Hmm, it's not entirely what I'd hoped for, but thanks anyway!

Comment (timowest) [inline querydsl-core/src/main/java/com/querydsl/core/types/ConstantImpl.java]: Could you be more specific then?

Comment (Shredder121) [inline querydsl-core/src/main/java/com/querydsl/core/types/ConstantImpl.java]: No it's fine, I just thought the diff would be a little more cleaner.
Since there is a new line introduced, git mismatches the lines a bit.

**Comment by Shredder121** [comment]
I finished the test, how does it look?

**Comment by johnktims** [comment]
Looks good to me now.
