### PR TITLE
Fix various issues caused by invalid parameter assumptions

### LINKED ISSUE #1413: Incorrect parameter values with Hibernate custom types.
We are using querydsl 3.x, and there lots of legacy columns in our JPA Entity mappings, because of this we had to use many hibernate custom types.

When there are 
- the same java type(like Boolean) but different custom types'(like yes_no, true_false) columns related conditions 
- and their  parameter values are the same (like Boolean.TRUE)
- and parameters' position number is the same in a query(like ?1),

Hibernate maps parameter values incorrectly.
This was reported already - https://github.com/querydsl/querydsl/issues/1168
Actually I think this is a bug of hibernate - https://hibernate.atlassian.net/browse/HHH-9871 .
But QueryDSL can work around this bug.

For exampe, when there are two or more boolean types(same java type) but they're custom types like the following(it doesn't matter that the colums are in the same entity or two or more entities),

``` java
@Type(type = "true_false")
@Column(name = "employee", columnDefinition = "char(1)")
 private Boolean employee;

@Type(type = "yes_no")
@Column(name = "male", columnDefinition = "char(1)")
private Boolean male;

@Column(name = "old")
private Boolean old;
```

And in a QueryDsl query has conditions with same java type and same value(Boolean.TRUE), QueryDsl generates JPQL like the follwing,

```
// employee == Booealn,TRUE, male == Boolean.TRUE, old == Boolean.FALSE
from User user where employee = ?1 and male = ?1 and old = ?2
```

**QueryDSL maps same java type value into same positional parameter.**

real parameter value mappings in hibernate is like the following

```
employee = 'T' and male = 'T' and old = false
```

_male parameter must have been 'Y' but it follows the first parameter value - 'T'._

employee and male columns have same java type but different custom types, QueryDsl maps same positional parameter(?1)  to these two columns.

**I wonder QueryDSL could map different poisitional parameters for every different condition even though they have same java type value(like Boolean.TRUE in the example).**

### LINKED ISSUE #1429: Reusing of constants in JPQL generation causes issues with hibernate query caching
I know it's actually an hibernate issue (I also created an issue for hibernate https://hibernate.atlassian.net/browse/HHH-9900) but maybe there is some workaround to avoid the problem I'm not aware of.

QueryDSL reuses constants when generating JPQL in com.mysema.query.jpa.JPQLSerializer.visitConstant(Object constant) thus the following JPAQuery:

```
new JPAQuery(entityManager).from(QCacheTes.cacheTest).where(QCacheTest.cacheTest.boola.eq(true).and(QCacheTest.cacheTest.boolb.eq(false)).and(QCacheTest.cacheTest.boolc.eq(true)))
```

results in the following JPQL:

```
select cacheTest from at.bluesource.CacheTest cacheTest WHERE cacheTest.boola = ?1 AND cacheTest.boolb = ?2 AND cacheTest.boolc = ?1
```

using the paramters:

```
{ 1=true, 2=false }
```

which is problematic when using hibernate query caching as described in the hibernate issue.

Is there any workaround I'm not aware of to avoid those problems? I thought about using Params instead of the raw values (which become constants in the JPAQuery) to avoid the reusing of constants but on the other hand it's not practical because I can't make sure that everybody always uses Params in out project. Maybe there's a way to configure QueryDSL to not reuse constants (after having a look at the code of QueryDSL I'm pretty sure there is no such way - at least in 3.6.4 which is the version we are currently using)? Or maybe there is a way to somehow magically 'convert' all constants to params just before generation of the JPQL query?

### LINKED ISSUE #2326: Use of Hibernate 5.3 and HibernateQuery results in "Could not locate named parameter"
The use of querydsl-jpa's HibernateQuery with Hibernate 5.3 will thrown an exception when you use parameters:
```
java.lang.IllegalArgumentException: Could not locate named parameter [1], expecting one of []

	at org.hibernate.query.internal.ParameterMetadataImpl.getNamedParameterDescriptor(ParameterMetadataImpl.java:218)
	at org.hibernate.query.internal.ParameterMetadataImpl.getQueryParameter(ParameterMetadataImpl.java:187)
	at org.hibernate.query.internal.QueryParameterBindingsImpl.getBinding(QueryParameterBindingsImpl.java:188)
	at org.hibernate.query.internal.AbstractProducedQuery.setParameter(AbstractProducedQuery.java:494)
	at org.hibernate.query.internal.AbstractProducedQuery.setParameter(AbstractProducedQuery.java:107)
	at com.querydsl.jpa.hibernate.HibernateUtil.setValue(HibernateUtil.java:91)
	at com.querydsl.jpa.hibernate.HibernateUtil.setConstants(HibernateUtil.java:79)
	at com.querydsl.jpa.hibernate.AbstractHibernateQuery.createQuery(AbstractHibernateQuery.java:105)
	at com.querydsl.jpa.hibernate.AbstractHibernateQuery.createQuery(AbstractHibernateQuery.java:97)
	at com.querydsl.jpa.hibernate.AbstractHibernateQuery.fetch(AbstractHibernateQuery.java:174)
	at com.querydsl.example.jpa.repository.TweetRepository.findAllWithHibernateQuery(TweetRepository.java:30)
	at com.google.inject.persist.jpa.JpaLocalTxnInterceptor.invoke(JpaLocalTxnInterceptor.java:66)
	at com.querydsl.example.jpa.repository.TweetRepositoryTest.find_list_by_predicate(TweetRepositoryTest.java:44)
```

I am not the only person experiencing this error, as @jpimag experienced the same issue:
https://github.com/querydsl/querydsl/pull/2283#issuecomment-399247423

To reproduce this issue, I modified the querydsl-example-jpa-guice example contained within the QueryDSL repository. You can find the patch here:
https://gist.github.com/andygoossens/5eed865ccfe84857f7e99ddb2dfb5790
Then just run test class `com.querydsl.example.jpa.repository.TweetRepositoryTest` and check whether it fails.

You can easily compare the different behaviour between Hibernate versions by altering the `<hibernate.version>` parameter in the POM file (part of the "hibernate5" profile). e.g. Hibernate version 5.2.17.Final works fine, but version 5.3.1.Final fails. Don't forget to activate the necessary Maven profile(s) of course! :-)

It looks like there is a mixup between named query parameters and positional query parameters. `getConstantToLabel()` could contain a constant with index "1" (as a String and meant to be used as `?1`) but QueryDSL is calling `Query<R> setParameter(String name, Object val);` meant for named parameters (like `:example`). Hibernate does not find the named parameter "1" and fails.

### LINKED ISSUE #2816: Generated JPA query with incorrect argument binding indexes
## Observed vs. expected behavior

Given an `JPA` entity with two boolean fields, one of them annotated with a custom type `@Type`, when querying by those two fields providing the same boolean value (`true, true` or `false, false`) the generated query ends up using `?1` for both arguments (as they are considered a constant).

The generated query is
```sql
select user
from User user
where user.active = ?1 and user.admin = ?1  -- note the two arguments as ?1
```
when the expected would be
```sql
select user
from User user
where user.active = ?1 and user.admin = ?2
```

## Steps to reproduce

Here is a sample application to reproduce the problem, with some tests and loggers enabled to show the differences between the generated query and the expected one.

https://github.com/didiez/hibernate-querydsl-type-binding-bug

## Environment

Querydsl version: **`4.4.0`**

Querydsl module: **`querydsl-jpa`**

Database: tested against `oracle 11g` and `h2` (probably database agnostic)

JDK: 11

## Additional details

Might be related to the changes applied to fix #2326 (PR #2354)

### PR DESCRIPTION
**Pull request by jwgmeligmeyling**
Reverts #2354
Fixes #2326
Fixes #2816
Fixes #1413
Fixes #1429
Closes #2000
Affects https://github.com/Blazebit/blaze-persistence/pull/1071

### CODE REVIEW

**Comment by F43nd1r** [comment]
looks good, if everything runs through. But why are tests running four times on this now?

**Comment by jwgmeligmeyling** [comment]
I think because I also push to the querydsl remote so I get both the push and pr builds, for both Java 8 and 11.

Its unrelated to the change.

**Comment by jwgmeligmeyling** [comment]
@F43nd1r it has proven surprisingly difficult to implement this properly.

HQL historically had two types of parameters: legacy positional parameters (`?`) and named parameters (`:test`). JPA currently describes to types of parameters implementors need to support as well: indexed parameters (`?1`, `?2`) and named parameters (`:test`). Hibernate recently dropped support for legacy positional parameters in favour of indexed parameters. Indexed parameters and named parameters cannot be mixed within the same query.

QueryDSL has two types of parameters: named parameters and anonymous parameters. While constants are usually serialized as parameters as well (unless literal rendering is enabled, which is currently only supported for querydsl-sql).

All constants for which a parameter is generated are stored with a unique key value in `constantToLabel`. While you would expect this label to be used for name of a named parameter, this is not the case. In JPA we always use indexed parameters. And the same applies to `querydsl-sql`, where  `constantToLabel` is unused and a list `constants` is maintained instead. In both cases, even when named parameters are explicitly provided in the query (through `new Param(Object.class, "name")`), this name is lost in the final query. While it would be nice to copy these explicitly provided parameter names to the final query, this would require us to put generated parameter names for the indexed parameter names in the query as indexed and named parameters usually cannot be mixed.

The entire setup in `constantToLabel` is solely used for two purposes:
- "attribute" names for the `CollQuerySerializer`. `CollQuerySerializer` executes queries in-memory and therefore compiles some Java code and thus needs "variables" to store the constants in.
- parameter names for `JDOQLSerializer`, as JDO does only seem to support named parameters and not indexed parameter, and thus a name needs to be generated if one is missing.

IMO it does not make sense to deal with `constantToLabel` in `SerializerBase` if its only applicable to two very specific dialects and only causes trouble for the other dialects.

I am currently trying to set up a new structure for `SerializerBase` that is both more easily extendable but also doesn't break any of the current dialects.

File: querydsl-core/src/main/java/com/querydsl/core/support/SerializerBase.java [hunk 1]
```diff
@@ -46,8 +58,9 @@
 
     private String anonParamPrefix = "_";
 
-    private Map<Object, String> constantToNamedLabel;
-    private Map<Object, Integer> constantToNumberedLabel;
+    protected final List<Object> constants = new LinkedList<>();
```
Comment (F43nd1r) [inline querydsl-core/src/main/java/com/querydsl/core/support/SerializerBase.java:61]: Is there a need for this? Seems like the only difference to `constantToLabel` keys is order, is that relevant?
Seems like it should be possible to use a single data structure instead of keeping two in sync.

**Review by F43nd1r — COMMENTED** [review]
Are all the fixed issues covered with old tests already? If not we could add some to prevent future regressions

File: querydsl-core/src/main/java/com/querydsl/core/support/SerializerBase.java (hunk 1 above)
Comment (jwgmeligmeyling) [reply querydsl-core/src/main/java/com/querydsl/core/support/SerializerBase.java:61]: Unfortunately it is not, and that is because `constantToLabel` works very differently across the various serializers for different dialects.

Constant to label is a mapping used primarily by JDO and CollQuerySerializer to create a unique label for unique objects and store them as a variable in the context of the query (so this is in fact not really a constant or a parameter at all).

As query parameters objects may occur different times using various mappings. Therefore the SQL serializer already maintained a list of constants instead of relying on constantToLabel. The proper fix was to use this for JPQL as well.

I did try to combine the two datastructures and it is possible as long as all labels are unique and the mapping is inverted to labelToConstant. However, this approach makes the implementation in SQL and JPQL overly complex and error prone (as this issues already show) and it also  defeats optimizations  that were deliberately made for JDO and CollQuerySerializer. In the end I just stumbled upon lots of overriden methods and serializer hacks to get all tests passing in all modules.

I am also worried that changing `constantToLabel` to `labelToConstant` is going to be a massive pain in the ass for integrators that implement different serializers based on this API or even use `getLabelToConstant()` for logging / parameter binding purposes  in their own applications.

This approach is simpler, more generic and only changes recently updated API's while leaving the API's that have been there for years in tact.

**Comment by jwgmeligmeyling** [comment]
* #2326 is tested simply by testing the examples / tests against Hibernate 5.3.
* #2816 is caused by #1429
* #1413 is caused by #1429
* #1429 is  tested by the changes in the asserted queries in the JPA integration

So no new tests are required beyond the altered tests in this PR.

**Review by F43nd1r — APPROVED** [review]
