### PR TITLE
[#2504] [#2053] Fix fetchResults for GROUP BY and HAVING in JPQL

### LINKED ISSUE #1614: JPA fetchCount() and group by not working
This is a bug resulting from this posting on Google Groups (see https://groups.google.com/forum/#!topic/querydsl/WH582YIY98I):

I found a strange problem with a rather complex group by query when it comes to counting the number of rows that will be returned for the query - the created HQL query contains a having clause (which is correct), but omits the group by clause (which is not correct and leads to an exception, stating that having was encountered without group by). I debugged the problem and found this code in JPQLSerializer.serialize():

```
    // group by
    if (!groupBy.isEmpty() && !forCountRow) {
        append(GROUP_BY).handle(COMMA, groupBy);
    }

    // having
    if (having != null) {
        append(HAVING).handle(having);
    }
```

My wish would be that a count query with group by + having would work, because I have a use case where I need exactly that. If that doesn't work out, then at least the having part should be omitted when fetchCount() is called.

Thanks in advance (for fixing this bug) and thanks for QueryDSL in general, which is truly awesome!

### LINKED ISSUE #2053: Fetching `QueryResults` from a query having both `groupBy` and `having` clause results in a `QuerySyntaxException`
Fetching `QueryResults` from a query having both `groupBy` and `having` clause results in a `QuerySyntaxException`. Here are two test cases, the first one executes without error the second results in the above described error: 

```
    @Test
    public void groupByHavingFetch() {
        QCustomer customer = QCustomer.customer;
        JPAQuery<Customer> customerQuery = new JPAQuery<Customer>(entityManager, HQLTemplates.DEFAULT).from(customer);

        customerQuery.groupBy(customer.lastName).having(customer.id.count().gt(1)).fetch();
    }

    @Test
    public void groupByHavingFetchResults() {
        QCustomer customer = QCustomer.customer;
        JPAQuery<Customer> customerQuery = new JPAQuery<Customer>(entityManager, HQLTemplates.DEFAULT).from(customer);

        customerQuery.groupBy(customer.lastName).having(customer.id.count().gt(1)).fetchResults();
    }
```
The test in error generates following error:

```
java.lang.IllegalArgumentException: org.hibernate.hql.internal.ast.QuerySyntaxException: unexpected token: having near line 3, column 1 [select count(distinct customer.lastName)
from Customer customer
having count(customer.id) > ?1]

	at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:131)
	at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:155)
	at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:162)
	at org.hibernate.internal.AbstractSharedSessionContract.createQuery(AbstractSharedSessionContract.java:662)
	at org.hibernate.internal.AbstractSessionImpl.createQuery(AbstractSessionImpl.java:23)
	at com.querydsl.jpa.impl.AbstractJPAQuery.createQuery(AbstractJPAQuery.java:101)
	at com.querydsl.jpa.impl.AbstractJPAQuery.fetchResults(AbstractJPAQuery.java:211)
	at GroupByHavingTest.groupByHavingFetchResults(GroupByHavingTest.java:49)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:51)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:237)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
Caused by: org.hibernate.hql.internal.ast.QuerySyntaxException: unexpected token: having near line 3, column 1 [select count(distinct customer.lastName)
from Customer customer
having count(customer.id) > ?1]
	at org.hibernate.hql.internal.ast.QuerySyntaxException.convert(QuerySyntaxException.java:74)
	at org.hibernate.hql.internal.ast.ErrorCounter.throwQueryException(ErrorCounter.java:91)
	at org.hibernate.hql.internal.ast.QueryTranslatorImpl.parse(QueryTranslatorImpl.java:288)
	at org.hibernate.hql.internal.ast.QueryTranslatorImpl.doCompile(QueryTranslatorImpl.java:187)
	at org.hibernate.hql.internal.ast.QueryTranslatorImpl.compile(QueryTranslatorImpl.java:142)
	at org.hibernate.engine.query.spi.HQLQueryPlan.<init>(HQLQueryPlan.java:115)
	at org.hibernate.engine.query.spi.HQLQueryPlan.<init>(HQLQueryPlan.java:77)
	at org.hibernate.engine.query.spi.QueryPlanCache.getHQLQueryPlan(QueryPlanCache.java:153)
	at org.hibernate.internal.AbstractSharedSessionContract.getQueryPlan(AbstractSharedSessionContract.java:545)
	at org.hibernate.internal.AbstractSharedSessionContract.createQuery(AbstractSharedSessionContract.java:654)
	... 32 more
``` 
The resulting hql Statement is missing the `groupBy` clause.

### LINKED ISSUE #2504: when groupBy with two fields,fetchCount throw exception
here is my code:

```
query.groupBy(_entity.field1,_entity.field2).fetchCount()
```

then the exception:

```
java.lang.IllegalArgumentException: org.hibernate.hql.internal.ast.QuerySyntaxException: expecting CLOSE, found ',' near line 1, column 56 [select count(distinct entity.field1, entity.field2)
from com.demo.core.domain.model.entity entity
where entity.field3 = ?1

	at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:133)
	at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:157)
	at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:164)
	at org.hibernate.internal.AbstractSharedSessionContract.createQuery(AbstractSharedSessionContract.java:670)
	at org.hibernate.internal.AbstractSessionImpl.createQuery(AbstractSessionImpl.java:23)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.orm.jpa.SharedEntityManagerCreator$SharedEntityManagerInvocationHandler.invoke(SharedEntityManagerCreator.java:305)
	at com.sun.proxy.$Proxy119.createQuery(Unknown Source)
	at com.querydsl.jpa.impl.AbstractJPAQuery.createQuery(AbstractJPAQuery.java:101)
	at com.querydsl.jpa.impl.AbstractJPAQuery.fetchCount(AbstractJPAQuery.java:81)
	at com.demo.core.infrastructure.repository.impl.queryRepositoryImpl.query(queryRepositoryImpl.java:91)
	at com.demo.core.infrastructure.repository.impl.queryRepositoryImplTest.query(queryRepositoryImplTest.java:25)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.springframework.test.context.junit4.statements.RunBeforeTestExecutionCallbacks.evaluate(RunBeforeTestExecutionCallbacks.java:73)
	at org.springframework.test.context.junit4.statements.RunAfterTestExecutionCallbacks.evaluate(RunAfterTestExecutionCallbacks.java:83)
	at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:75)
	at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:86)
	at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:84)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:251)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:97)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:190)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: org.hibernate.hql.internal.ast.QuerySyntaxException: expecting CLOSE, found ',' near line 1, column 56 [select count(distinct entity.field1, entity.field2)
from com.demo.core.domain.model.rebate.entity entity
where entity.field3 = ?1
	at org.hibernate.hql.internal.ast.QuerySyntaxException.convert(QuerySyntaxException.java:74)
	at org.hibernate.hql.internal.ast.ErrorCounter.throwQueryException(ErrorCounter.java:91)
	at org.hibernate.hql.internal.ast.QueryTranslatorImpl.parse(QueryTranslatorImpl.java:291)
	at org.hibernate.hql.internal.ast.QueryTranslatorImpl.doCompile(QueryTranslatorImpl.java:186)
	at org.hibernate.hql.internal.ast.QueryTranslatorImpl.compile(QueryTranslatorImpl.java:141)
	at org.hibernate.engine.query.spi.HQLQueryPlan.<init>(HQLQueryPlan.java:115)
	at org.hibernate.engine.query.spi.HQLQueryPlan.<init>(HQLQueryPlan.java:77)
	at org.hibernate.engine.query.spi.QueryPlanCache.getHQLQueryPlan(QueryPlanCache.java:153)
	at org.hibernate.internal.AbstractSharedSessionContract.getQueryPlan(AbstractSharedSessionContract.java:553)
	at org.hibernate.internal.AbstractSharedSessionContract.createQuery(AbstractSharedSessionContract.java:662)
	... 41 more
```

and when I remove one field in the groupBy, the same code will success

so what's the problem?

### PR DESCRIPTION
**Pull request by jwgmeligmeyling**
Fixes #2504 
Fixes #2053
Fixes #1614

Ideally JPA users should just use `fetch()` and not `fetchResults()` , particularly when the query involves a `GROUP BY` or `HAVING` clause. For `fetchCount()` there is no viable alternative to point users to, although users should be aware that `fetchCount()` for queries with a `GROUP BY` or `HAVING` clause is just as slow as fetching the entire query.

Also supersedes #1619. That patch naively moves the HAVING clause to the WHERE clause, but this will fail for some types of expressions (i.e. aggregate functions). As a result that patch still fails to resolve most of the issues.

See Slack: https://querydsl.slack.com/archives/C06KLG1BP/p1590961415105400

### CODE REVIEW

File: querydsl-jpa/src/main/java/com/querydsl/jpa/impl/AbstractJPAQuery.java [hunk 1]
```diff
@@ -208,10 +214,20 @@ private Object getSingleResult(Query query) {
     @Override
     public QueryResults<T> fetchResults() {
```
Comment (johnktims) [inline querydsl-jpa/src/main/java/com/querydsl/jpa/impl/AbstractJPAQuery.java:215]: Should we deprecate `fetchResults`? It's easy to fetch the count separately if the user wants it.

Comment (jwgmeligmeyling) [reply querydsl-jpa/src/main/java/com/querydsl/jpa/impl/AbstractJPAQuery.java:215]: `QueryResults` seems to be a very intentional QueryDSL API. 

I think is mostly an unfortunate naming decision in QueryDSL 4. `list()` was way more recognizable than `fetch()`, so users would less likely unintentionally end up calling `listReslults()` instead of `fetchResults()`.

Its even more problematic in JPA where you also have `fetchJoin` which adds the FETCH join specifier for initializing associations with the query. Having both `fetch()` and `fetchJoin` makes the methods even more ambiguous.

Personally I'd really like to rename `fetch()` to `fetchResults()` and `fetchResults()` to something like `fetchQueryResults()` (or remove it altogether), but its going to be a rather breaking change. Definitely only possible for 5.x and even then probably not received fairly well with users struggling with once again porting their application.

I am not sure what to do at this point, but I would be fine with deprecating `fetchResults()`. At least that gives us a mechanism to direct users to use `fetch()`  instead. However, I am not sure if deprecating `fetchResults` makes sense if we do not intend to remove or rename it eventually. I am not sure how widely it is "actively" used.

Comment (idosal) [reply querydsl-jpa/src/main/java/com/querydsl/jpa/impl/AbstractJPAQuery.java:215]: I think deprecating it now makes sense. Then we'd be able to rename it/remove it in 5.X or 6.X.

Comment (jwgmeligmeyling) [reply querydsl-jpa/src/main/java/com/querydsl/jpa/impl/AbstractJPAQuery.java:215]: And then deprecate it on `AbstractJPAQuery` only or `Fetchable`? (the latter would also affect `querydsl-sql` and others, which might support `fetchResults()` just fine)

Comment (johnktims) [reply querydsl-jpa/src/main/java/com/querydsl/jpa/impl/AbstractJPAQuery.java:215]: I would deprecate it on `Fetchable`. `fetchResults` might work correctly in other modules, but, in my opinion, the method just creates confusion and unwanted side effects over functionality that could easily be added in the application.

File: querydsl-jpa/src/main/java/com/querydsl/jpa/impl/AbstractJPAQuery.java [hunk 2]
```diff
@@ -78,6 +78,12 @@ public AbstractJPAQuery(EntityManager em, JPQLTemplates templates, QueryMetadata
     @Override
     public long fetchCount() {
         try {
+            if (getMetadata().getGroupBy().size() > 1 || getMetadata().getHaving() != null) {
+                logger.warn("Fetch count is computing count in memory!");
+                Query query = createQuery(null, false);
```
Comment (gudaoxuri) [inline querydsl-jpa/src/main/java/com/querydsl/jpa/impl/AbstractJPAQuery.java:83]: I think we can convert hql to native sql and add select count(1) , my solution example ：
 https://github.com/querydsl/querydsl/issues/2504#issuecomment-666888659

Comment (jwgmeligmeyling) [reply querydsl-jpa/src/main/java/com/querydsl/jpa/impl/AbstractJPAQuery.java:83]: That approach works only with Hibernate - not plain JPA, and only if there is a one-to-one mapping between your HQL parameters and SQL parameters, which isn't always the case (for example when a named parameter is reused in the query).

If you need reliable count queries I encourage you to use Blaze-Persistence, which has an awesome mechanism of converting any query to its count query. It also integrates with Querydsl (the `blaze-persistence-querydsl` module): https://persistence.blazebit.com/documentation/1.5/core/manual/en_US/index.html#querydsl-integration .

Using a BlazeJPAQuery instead of a JPAQuery both `fetchResults` and `fetchCount` work reliably again.

File: querydsl-jpa/src/main/java/com/querydsl/jpa/impl/AbstractJPAQuery.java (hunk 1 above)
Comment (jwgmeligmeyling) [reply querydsl-jpa/src/main/java/com/querydsl/jpa/impl/AbstractJPAQuery.java:272]: I've deprecated it on `AbstractJPAQuery` and added a detailed description in the Javadoc regarding rationale and alternatives.
