### PR TITLE
Fix end position handling

### LINKED ISSUE #1921: can't use addFlag(Postion.END when using new bulk insert
I want to generate the following query (which is a valid mysql query) : 
```
insert into `table` (`k`, `v`) values (1, 1), (2, 2) on duplicate key update v = values(v);
```
I manage to generate the multiple values insert batch thanks to #1899 however the `addFlag( QueryFlag.Position.END` is not appended. Exemple query : 
```
            SQLInsertClause clause = new SQLInsertClause(con, dbTplConf, t_rank);
            clause.setBatchToBulk(true);
            for (GoogleRank rank : ranks) {
                clause
                    .set(t_rank.k, rank.k)
                    .set(t_rank.v, rank.v)
                    .addBatch();
            }
            clause.addFlag(QueryFlag.Position.END," on duplicate key update v = values(v) ");    
```

### PR DESCRIPTION
**Pull request by timowest**
Fixes #1921 

Fixes also toString() and getSQL() for the batchToBulk mode

### CODE REVIEW

File: querydsl-sql/src/test/java/com/querydsl/sql/dml/SQLInsertClauseTest.java [hunk 1]
```diff
@@ -31,6 +32,21 @@ public void getSQL() {
...
+    public void bulk() {
+        QEmployee emp1 = new QEmployee("emp1");
+        SQLInsertClause insert = new SQLInsertClause(null, SQLTemplates.DEFAULT, emp1);
+        insert.set(emp1.id, 1);
+        insert.addBatch();
+        insert.set(emp1.id, 2);
+        insert.addBatch();
+        insert.addFlag(QueryFlag.Position.END, " on duplicate key ignore");
+        insert.setBatchToBulk(true);
+        assertEquals("nsert into EMPLOYEE (ID)\n" +
```
Comment (Shredder121) [inline querydsl-sql/src/test/java/com/querydsl/sql/dml/SQLInsertClauseTest.java]: Typo?

**Comment by Shredder121** [comment]
Looks good to me. :+1:
