### PR TITLE
Fix empty value handling

### LINKED ISSUE #1810: Don't skip null prefix/suffix values in Maven goals
Related to https://groups.google.com/forum/#!topic/querydsl/HupqtP28LRM

Also related http://mail-archives.apache.org/mod_mbox/maven-users/200708.mbox/%3C5a2cf1f60708090246l216f156esf46cc1e968b37ccd@mail.gmail.com%3E

### PR DESCRIPTION
**Pull request by timowest**
Fixes #1810

### CODE REVIEW

**Comment by Shredder121** [comment]
This doesn't actually fix it.
Looking into a fix.

**Comment by Shredder121** [comment]
[I found the culprit][culprit].
The value must be nonempty, otherwise it falls back to the `default-value`.

What we could do is maybe recognize `BLANK` (case insensitive?).

[culprit]: http://grepcode.com/file/repo1.maven.org/maven2/org.eclipse.sisu/org.eclipse.sisu.plexus/0.3.0/org/codehaus/plexus/component/configurator/converters/basic/AbstractBasicConverter.java#AbstractBasicConverter.fromExpression%28org.codehaus.plexus.configuration.PlexusConfiguration%2Corg.codehaus.plexus.component.configurator.expression.ExpressionEvaluator%2Cjava.lang.Class%29

**Comment by Shredder121** [comment]
It's been about a month ago, what's your view on my suggestion?

**Comment by timowest** [comment]
I can't come up with anything better, so `BLANK`is fine. Can you do the change?

File: querydsl-maven-plugin/src/main/java/com/querydsl/maven/AbstractMetaDataExportMojo.java [hunk 1]
```diff
@@ -394,18 +395,10 @@ public void execute() throws MojoExecutionException, MojoFailureException {
...
-            if (beanPrefix != null) {
-                exporter.setBeanPrefix(beanPrefix);
-            }
-            if (beanSuffix != null) {
-                exporter.setBeanSuffix(beanSuffix);
-            }
+            exporter.setNamePrefix(emptyIfSetToBlank(namePrefix));
+            exporter.setNameSuffix(Strings.nullToEmpty(nameSuffix));
+            exporter.setBeanPrefix(Strings.nullToEmpty(beanPrefix));
+            exporter.setBeanSuffix(Strings.nullToEmpty(beanSuffix));
```
Comment (Shredder121) [inline querydsl-maven-plugin/src/main/java/com/querydsl/maven/AbstractMetaDataExportMojo.java]: I figured changing it also for these is not necessary, since only `namePrefix` has a `default-value` set to a non-empty String.

**Comment by Shredder121** [comment]
I was looking into a custom `@configurator`, using an extra doclet `@nullable` that would actually set things to null if the aren't supplied.
Alas, it didn't work well enough to warrant the change.
