### PR TITLE
[fixes #2579] fix: added `forCount` conditional statement for skip transform logic when countQuery

### LINKED ISSUE #2579: [BUG & Solve] JpaSQLQuery `fetchResults` illegal statement Exception
## Bug Solve Demo link
https://github.com/heesuk-ahn/querydsl-4.3.1-fetchresult-issue-debug

## Problem

If `fetchResults` is called using` JpaSQLQuery`, illegalArgumentException occurs.

## Description

When calling `fetchResults`, the` count` query is called beforehand.

If `ResultTransform` is set to receive the result value of the query as a desired object, illegalException occurs.

Why is this error occurring?

The reason is that you want to convert the result value of the count query that is executed in advance to `ResultTransform`.

To reproduce this error condition, I created the `projections.bean` test for FactoryExpression as below.

```
public QueryResults<BookName> getBooksWithProjectionFromJPASQL(int offset, int limit) {
        SQLTemplates oracleTemplate = OracleTemplates.builder().printSchema().build();
        JPAHelper jpaHelper = new JPAHelper(emf.createEntityManager(), oracleTemplate);

        Map<String, Expression<?>> bindings = new HashMap<>();
        bindings.put("name", book.name);

        return jpaHelper.query()
                        .select(Projections.bean(BookName.class, bindings))
                        .from(book)
                        .offset(offset)
                        .limit(limit)
                        .fetchResults();
    }
```

When fetchResults is called, the following code is executed.

```
 private Query createQuery(boolean forCount) {
         NativeSQLSerializer serializer = (NativeSQLSerializer) serialize(forCount);
         String queryString = serializer.toString();
         logQuery(queryString, serializer.getConstantToAllLabels());
         Expression<?> projection = queryMixin.getMetadata().getProjection();
         Query query;

         .
         .
         .
         . [!] code line 161 - 165       
         if (projection instanceof FactoryExpression) {
             if (!queryHandler.transform(query, (FactoryExpression<?>) projection)) {
                 this.projection = (FactoryExpression<?>) projection;
             }
         }
 
         return query;
     }
```

Let's look at the logic of code line 161 of the createQuery function.

What code lines 161-165 mean is applying a `ResultTransform` for projection

__But the problem here is that the forCount query must `skip` this logic.__

If skip is not performed, ResultTransform is applied to forCount query, and `illegalArgumentException` occurs.

## My Suggest

To solve this problem, I simply added `!ForCount` to conditional statement.

## Integration Test

After changing the code as below, I created a querydsl-jpa snapshot jar and added it to the external lib.

```
[Fixed]

.
.
. code line 161
 if (!forCount && projection instanceof FactoryExpression) { <---- added !forCount
    if (!queryHandler.transform(query, (FactoryExpression<?>) projection)) {
        this.projection = (FactoryExpression<?>) projection;
    }
 }
```

And I could confirm that the below test works normally.

```
    @Test
    public void should_Get_Books_With_Projection_From_JPASQL() {
        final int offset = 0;
        final int limit = 10;

        executeQueryForInsert(emf.createEntityManager(), firstBook);

        QueryResults<BookName> bookNames = bookRepository.getBooksWithProjectionFromJPASQL(offset, limit);

        assertThat(bookNames.getResults().get(0).getName()).isEqualTo(bookName);
    }
```

### PR DESCRIPTION
**Pull request by heesuk-ahn**
## solve demo link

* https://github.com/heesuk-ahn/querydsl-4.3.1-fetchresult-issue-debug

## Check Issue

* #2579

### CODE REVIEW

**Comment by johnktims** [comment]
Would you mind adding the tests you wrote in the issue? Also, It looks like you branched from `master` when the CI was broken so you'll need to rebase. Sorry for the hassle.

**Comment by heesuk-ahn** [comment]
@johnktims You're welcome :)

I will do it as soon as possible.

TODO)

* should add test code for this issue
* rebase code

If you have any other thoughts, please comment. :)

**Comment by jwgmeligmeyling** [comment]
While adding a test, please also have a look how it handles queries with multiple group by clauses or a having clause. For JPA (non-SQL) queries, this causes various issues (#2504, #2053).

**Comment by heesuk-ahn** [comment]
@jwgmeligmeyling Thanks for the good comments.

I also added a test for group and having. :)

**Comment by heesuk-ahn** [comment]
humm..

It says that `start test database` is broken. Do you know anything about this issue?

(https://github.com/querydsl/querydsl/pull/2580/checks?check_run_id=809917861)

@johnktims @jwgmeligmeyling

**Comment by johnktims** [comment]
@heesuk-ahn It occasionally times out. I restarted the build and the test databases started correctly this time.

File: querydsl-jpa/src/test/java/com/querydsl/jpa/JPASQLBase.java [hunk 1]
```diff
@@ -86,10 +90,49 @@ public void entityQueries_createQuery() {
...
+    }
+
+    @Test
+    public void should_get_black_cat_count_by_using_group_by_and_having() {
+        final long expectedBlackCatCount = 6L;
+
+        final long actualBlackCatCount = query().from(cat)
+                                                .select(catEntity.name.count())
+                                                .groupBy(catEntity.color)
+                                                .having(catEntity.name.count().goe(1))
```
Comment (jwgmeligmeyling) [inline querydsl-jpa/src/test/java/com/querydsl/jpa/JPASQLBase.java:132]: This having clause is not entropy reducing, so even if its handled correcly, the query gives the proper result.

Comment (heesuk-ahn) [reply querydsl-jpa/src/test/java/com/querydsl/jpa/JPASQLBase.java:132]: How should I test it? Can you give me a comment~? 🤔

Comment (jwgmeligmeyling) [reply querydsl-jpa/src/test/java/com/querydsl/jpa/JPASQLBase.java:132]: `catEntity.name.count()` can never be 0. It is minimally 1. But it can be higher than 1. Not sure if that occurs in your test data. The point is, `catEntity.name.count() >= 1` will never filter any rows. Therefore you can't know whether the having clause was properly handled. It would be interesting to see what happens for `catEntity.name.count() >= 2`. It should return a non empty result (the ones   with `count() >= 2`), and eliminate the results with `count() = 1`). The latter for example doesn't happen in JPA currently. It doesn't handle the having clause at all. Therefore count queries with a HAVING clause are fundamentally broken in JPQL (not JPA SQL), and it would be interesting to see how this behaves in JPA SQL.

Comment (heesuk-ahn) [reply querydsl-jpa/src/test/java/com/querydsl/jpa/JPASQLBase.java]: Thanks for sharing your thoughts. :)

I have created two additional test data to check the having clause more accurately. (tabbyColorCatFoo, tabbyColorCatBar)

The total test data were 6 black cats and 2 Tabby cats.

And I wrote the query as below.

```
final long actualTabbyCatCount = query().from(cat)
                                                                      .select(catEntity.name.count())
                                                                      .groupBy(catEntity.color)
                                                                      .having(catEntity.name.count().eq(2L))
                                                                      .fetchOne();

assertEquals(expectedTabbyCatCount, actualTabbyCatCount); //true
```

**Comment by jwgmeligmeyling** [comment]
Thanks for your changes @heesuk-ahn , I'll review it tomorrow!

**Comment by heesuk-ahn** [comment]
if you'll execuse me, any update :) ~?
